env: "gymma"

env_args:
  key: "MultiAgentEthicalGathering-large-v1"
  time_limit: 500
  pretrained_wrapper: null

test_greedy: False
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 25000000
common_reward: False
save_model: False # Save the models to disk
save_model_interval: 50000 # Save models after this many timesteps