env: "gymmoma"

env_args:
  key: "MultiAgentEthicalGathering-large-mo-v1"
  time_limit: 500
  pretrained_wrapper: null
  efficiency: 0.4
  donation_capacity: 10

test_greedy: False
test_nepisode: 300
test_interval: 5000000
log_interval: 5000000
runner_log_interval: 2000000
learner_log_interval: 2000000
t_max: 25000000
common_reward: False
save_model: True # Save the models to disk
save_model_interval: 15000000 # Save models after this many timesteps