env: "gymmoma"

env_args:
  key: "MultiAgentEthicalGathering-large-mo-v1"
  time_limit: 500
  pretrained_wrapper: null

test_greedy: False
test_nepisode: 500
test_interval: 10000000
log_interval: 5000000
runner_log_interval: 50000
learner_log_interval: 50000
t_max: 50000000
common_reward: False
save_model: True # Save the models to disk
save_model_interval: 10000000 # Save models after this many timesteps