exclude: null
grid-search:

  "--config":
    - "ippo_egg_mo"

  lr:
    - 0.003
    - 0.0003
    - 0.005
    - 0.0005

  standardise_rewards:
    - True

  use_rnn:
    - False

  entropy_coef:
    - 0.12

grid-search-groups:
  env0:
    - "--env-config": "egg_large_mo"
